export interface Extra {
  id: number
  name: string
  description?: string
  category: string
  unitType: string
  billingUnit?: string // New: Unidade de cobrança
  applicationType?: string // New: Tipo de aplicação
  cost: number
  status: 1 | 0
}

export const EXTRA_CATEGORIES = [
  "Acabamentos",
  "Têxteis",
  "Comunicação Visual",
  "Embalagens",
  "Impressão",
  "Merchandising",
  "Decoração",
  "Linha Sustentável",
] as const

export const BILLING_UNITS = ["unidade", "folha", "plano", "m²", "metro", "hora"] as const

export const APPLICATION_TYPES = ["Por peça", "Por lote", "Por folha", "Por área", "Outro"] as const

export const mockExtras: Extra[] = [
  // Acabamentos de Impressão
  {
    id: 1,
    name: "Laminação Brilho",
    description: "Acabamento com película brilhante para proteção e realce visual",
    category: "Acabamentos",
    unitType: "m²",
    billingUnit: "m²",
    applicationType: "Por área",
    cost: 2.5,
    status: 1,
  },
  {
    id: 2,
    name: "Laminação Mate",
    description: "Acabamento com película mate para aspecto elegante e sofisticado",
    category: "Acabamentos",
    unitType: "m²",
    billingUnit: "m²",
    applicationType: "Por área",
    cost: 2.5,
    status: 1,
  },
  {
    id: 3,
    name: "Verniz UV",
    description: "Verniz ultravioleta para proteção e brilho intenso",
    category: "Acabamentos",
    unitType: "m²",
    billingUnit: "m²",
    applicationType: "Por área",
    cost: 3.8,
    status: 1,
  },
  {
    id: 4,
    name: "Verniz Seletivo",
    description: "Aplicação de verniz em áreas específicas para destaque",
    category: "Acabamentos",
    unitType: "m²",
    billingUnit: "m²",
    applicationType: "Por área",
    cost: 5.2,
    status: 1,
  },
  {
    id: 5,
    name: "Hot Stamping Dourado",
    description: "Aplicação de folha dourada a quente para acabamento premium",
    category: "Acabamentos",
    unitType: "m²",
    billingUnit: "m²",
    applicationType: "Por área",
    cost: 8.5,
    status: 1,
  },
  {
    id: 6,
    name: "Hot Stamping Prateado",
    description: "Aplicação de folha prateada a quente para acabamento premium",
    category: "Acabamentos",
    unitType: "m²",
    billingUnit: "m²",
    applicationType: "Por área",
    cost: 8.5,
    status: 1,
  },
  {
    id: 7,
    name: "Relevo Seco",
    description: "Relevo sem tinta para efeito tátil elegante",
    category: "Acabamentos",
    unitType: "m²",
    billingUnit: "m²",
    applicationType: "Por área",
    cost: 6.0,
    status: 1,
  },
  // Corte e Dobragem
  {
    id: 8,
    name: "Corte Laser",
    description: "Corte de precisão com tecnologia laser",
    category: "Acabamentos",
    unitType: "hora",
    billingUnit: "hora",
    applicationType: "Por lote",
    cost: 45.0,
    status: 1,
  },
  {
    id: 9,
    name: "Corte Especial",
    description: "Corte personalizado em formas não convencionais",
    category: "Acabamentos",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 0.25,
    status: 1,
  },
  {
    id: 10,
    name: "Vinco",
    description: "Marcação para facilitar dobragem precisa",
    category: "Acabamentos",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 0.15,
    status: 1,
  },
  {
    id: 11,
    name: "Dobragem Simples",
    description: "Dobragem em uma ou duas dobras",
    category: "Acabamentos",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 0.08,
    status: 1,
  },
  {
    id: 12,
    name: "Dobragem Complexa",
    description: "Dobragem com múltiplas dobras ou formatos especiais",
    category: "Acabamentos",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 0.18,
    status: 1,
  },
  // Encadernação
  {
    id: 13,
    name: "Agrafos",
    description: "Encadernação com agrafos metálicos",
    category: "Acabamentos",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 0.12,
    status: 1,
  },
  {
    id: 14,
    name: "Wire-O",
    description: "Encadernação com espiral metálica",
    category: "Acabamentos",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 1.5,
    status: 1,
  },
  {
    id: 15,
    name: "Capa Dura",
    description: "Encadernação com capa rígida",
    category: "Acabamentos",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 4.5,
    status: 1,
  },
  {
    id: 16,
    name: "Cola Quente",
    description: "Encadernação com cola termofusível",
    category: "Acabamentos",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 0.85,
    status: 1,
  },
  // Personalização Têxtil
  {
    id: 17,
    name: "Serigrafia 1 Cor",
    description: "Impressão serigráfica com uma cor",
    category: "Têxteis",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 1.2,
    status: 1,
  },
  {
    id: 18,
    name: "Serigrafia Multicolor",
    description: "Impressão serigráfica com múltiplas cores",
    category: "Têxteis",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 2.5,
    status: 1,
  },
  {
    id: 19,
    name: "Bordado",
    description: "Personalização com bordado em linha",
    category: "Têxteis",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 3.5,
    status: 1,
  },
  {
    id: 20,
    name: "Transfer Digital",
    description: "Aplicação de transfer impresso digitalmente",
    category: "Têxteis",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 2.0,
    status: 1,
  },
  {
    id: 21,
    name: "Sublimação",
    description: "Impressão por sublimação para cores vibrantes",
    category: "Têxteis",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 2.8,
    status: 1,
  },
  // Montagem e Instalação
  {
    id: 22,
    name: "Montagem Roll-Up",
    description: "Montagem de estrutura roll-up com impressão",
    category: "Comunicação Visual",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 5.0,
    status: 1,
  },
  {
    id: 23,
    name: "Instalação Vinil",
    description: "Serviço de instalação de vinil autocolante",
    category: "Comunicação Visual",
    unitType: "m²",
    billingUnit: "m²",
    applicationType: "Por área",
    cost: 8.0,
    status: 1,
  },
  {
    id: 24,
    name: "Instalação Lona",
    description: "Serviço de instalação de lona publicitária",
    category: "Comunicação Visual",
    unitType: "m²",
    billingUnit: "m²",
    applicationType: "Por área",
    cost: 12.0,
    status: 1,
  },
  // Embalagem
  {
    id: 25,
    name: "Embalagem Individual",
    description: "Embalagem individual em plástico ou papel",
    category: "Embalagens",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 0.15,
    status: 1,
  },
  {
    id: 26,
    name: "Caixa Personalizada",
    description: "Caixa de cartão personalizada para embalagem",
    category: "Embalagens",
    unitType: "unidade",
    billingUnit: "unidade",
    applicationType: "Por peça",
    cost: 1.2,
    status: 0,
  },
]
