export interface Product {
  id: number
  name: string
  reference: string
  category: string
  subcategory: string
  unitType: string
  baseCost: number
  defaultMargin: number
  status: 1 | 0
}

export const mockProducts: Product[] = [
  // Impressão Gráfica Tradicional
  {
    id: 1,
    name: "Cartões de Visita",
    reference: "CV-001",
    category: "Impressão Gráfica Tradicional",
    subcategory: "Cartões",
    unitType: "unidade",
    baseCost: 0.15,
    defaultMargin: 150,
    status: 1,
  },
  {
    id: 2,
    name: "Flyers A5",
    reference: "FL-A5-001",
    category: "Impressão Gráfica Tradicional",
    subcategory: "Flyers",
    unitType: "unidade",
    baseCost: 0.25,
    defaultMargin: 120,
    status: 1,
  },
  {
    id: 3,
    name: "Cartazes A3",
    reference: "CT-A3-001",
    category: "Impressão Gráfica Tradicional",
    subcategory: "Cartazes",
    unitType: "unidade",
    baseCost: 2.5,
    defaultMargin: 100,
    status: 1,
  },
  {
    id: 4,
    name: "Brochuras A4",
    reference: "BR-A4-001",
    category: "Impressão Gráfica Tradicional",
    subcategory: "Brochuras",
    unitType: "unidade",
    baseCost: 1.8,
    defaultMargin: 110,
    status: 1,
  },
  {
    id: 5,
    name: "Papel Timbrado A4",
    reference: "PT-A4-001",
    category: "Impressão Gráfica Tradicional",
    subcategory: "Papel Timbrado",
    unitType: "unidade",
    baseCost: 0.35,
    defaultMargin: 130,
    status: 1,
  },
  {
    id: 6,
    name: "Blocos de Notas A5",
    reference: "BN-A5-001",
    category: "Impressão Gráfica Tradicional",
    subcategory: "Blocos",
    unitType: "unidade",
    baseCost: 3.5,
    defaultMargin: 90,
    status: 1,
  },
  {
    id: 7,
    name: "Calendários de Parede",
    reference: "CL-PAR-001",
    category: "Impressão Gráfica Tradicional",
    subcategory: "Calendários",
    unitType: "unidade",
    baseCost: 4.2,
    defaultMargin: 85,
    status: 1,
  },
  // Têxteis Personalizados
  {
    id: 8,
    name: "T-shirts Algodão",
    reference: "TS-ALG-001",
    category: "Têxteis Personalizados",
    subcategory: "T-shirts",
    unitType: "unidade",
    baseCost: 5.5,
    defaultMargin: 120,
    status: 1,
  },
  {
    id: 9,
    name: "Sweatshirts",
    reference: "SW-001",
    category: "Têxteis Personalizados",
    subcategory: "Sweatshirts",
    unitType: "unidade",
    baseCost: 12.0,
    defaultMargin: 100,
    status: 1,
  },
  {
    id: 10,
    name: "Bonés Bordados",
    reference: "BC-BOR-001",
    category: "Têxteis Personalizados",
    subcategory: "Bonés",
    unitType: "unidade",
    baseCost: 6.5,
    defaultMargin: 110,
    status: 1,
  },
  {
    id: 11,
    name: "Polos Piqué",
    reference: "PL-PIQ-001",
    category: "Têxteis Personalizados",
    subcategory: "Polos",
    unitType: "unidade",
    baseCost: 8.5,
    defaultMargin: 105,
    status: 1,
  },
  {
    id: 12,
    name: "Sacos de Pano",
    reference: "SC-PAN-001",
    category: "Têxteis Personalizados",
    subcategory: "Sacos",
    unitType: "unidade",
    baseCost: 2.8,
    defaultMargin: 140,
    status: 1,
  },
  // Comunicação Visual & Grande Formato
  {
    id: 13,
    name: "Lonas Publicitárias",
    reference: "LN-PUB-001",
    category: "Comunicação Visual & Grande Formato",
    subcategory: "Lonas",
    unitType: "m²",
    baseCost: 15.0,
    defaultMargin: 80,
    status: 1,
  },
  {
    id: 14,
    name: "Vinil Autocolante",
    reference: "VN-AUT-001",
    category: "Comunicação Visual & Grande Formato",
    subcategory: "Vinil",
    unitType: "m²",
    baseCost: 12.5,
    defaultMargin: 90,
    status: 1,
  },
  {
    id: 15,
    name: "Roll-ups 85x200cm",
    reference: "RU-85-001",
    category: "Comunicação Visual & Grande Formato",
    subcategory: "Roll-ups",
    unitType: "unidade",
    baseCost: 45.0,
    defaultMargin: 75,
    status: 1,
  },
  {
    id: 16,
    name: "Banners X-Banner",
    reference: "BN-XBN-001",
    category: "Comunicação Visual & Grande Formato",
    subcategory: "Banners",
    unitType: "unidade",
    baseCost: 35.0,
    defaultMargin: 80,
    status: 1,
  },
  {
    id: 17,
    name: "Placas PVC 5mm",
    reference: "PL-PVC-001",
    category: "Comunicação Visual & Grande Formato",
    subcategory: "Placas",
    unitType: "m²",
    baseCost: 25.0,
    defaultMargin: 85,
    status: 1,
  },
  // Merchandising / Objetos Promocionais
  {
    id: 18,
    name: "Canecas Cerâmica",
    reference: "CN-CER-001",
    category: "Merchandising / Objetos Promocionais",
    subcategory: "Canecas",
    unitType: "unidade",
    baseCost: 3.2,
    defaultMargin: 150,
    status: 1,
  },
  {
    id: 19,
    name: "Canetas Metálicas",
    reference: "CP-MET-001",
    category: "Merchandising / Objetos Promocionais",
    subcategory: "Canetas",
    unitType: "unidade",
    baseCost: 0.85,
    defaultMargin: 180,
    status: 1,
  },
  {
    id: 20,
    name: "Chaveiros Personalizados",
    reference: "CH-PER-001",
    category: "Merchandising / Objetos Promocionais",
    subcategory: "Chaveiros",
    unitType: "unidade",
    baseCost: 1.2,
    defaultMargin: 160,
    status: 1,
  },
  {
    id: 21,
    name: "Powerbanks 5000mAh",
    reference: "PB-5K-001",
    category: "Merchandising / Objetos Promocionais",
    subcategory: "Powerbanks",
    unitType: "unidade",
    baseCost: 8.5,
    defaultMargin: 95,
    status: 1,
  },
  {
    id: 22,
    name: "Bolsas Térmicas",
    reference: "BL-TER-001",
    category: "Merchandising / Objetos Promocionais",
    subcategory: "Bolsas",
    unitType: "unidade",
    baseCost: 4.5,
    defaultMargin: 120,
    status: 0,
  },
  // Embalagens Personalizadas
  {
    id: 23,
    name: "Caixas Cartão Canelado",
    reference: "CX-CAN-001",
    category: "Embalagens Personalizadas",
    subcategory: "Caixas",
    unitType: "unidade",
    baseCost: 1.8,
    defaultMargin: 110,
    status: 1,
  },
  {
    id: 24,
    name: "Sacos de Papel Kraft",
    reference: "SP-KRA-001",
    category: "Embalagens Personalizadas",
    subcategory: "Sacos",
    unitType: "unidade",
    baseCost: 0.45,
    defaultMargin: 140,
    status: 1,
  },
  {
    id: 25,
    name: "Rótulos Adesivos",
    reference: "RT-ADE-001",
    category: "Embalagens Personalizadas",
    subcategory: "Rótulos",
    unitType: "unidade",
    baseCost: 0.12,
    defaultMargin: 170,
    status: 1,
  },
  // Linha Sustentável
  {
    id: 26,
    name: "Papel Reciclado A4",
    reference: "PR-REC-001",
    category: "Linha Sustentável",
    subcategory: "Papéis Reciclados",
    unitType: "kg",
    baseCost: 2.5,
    defaultMargin: 100,
    status: 1,
  },
  {
    id: 27,
    name: "T-shirts Algodão Orgânico",
    reference: "TS-ORG-001",
    category: "Linha Sustentável",
    subcategory: "Têxteis Orgânicos",
    unitType: "unidade",
    baseCost: 8.5,
    defaultMargin: 110,
    status: 1,
  },
  {
    id: 28,
    name: "Canetas Bambu",
    reference: "CP-BAM-001",
    category: "Linha Sustentável",
    subcategory: "Merchandising Ecológico",
    unitType: "unidade",
    baseCost: 1.5,
    defaultMargin: 150,
    status: 1,
  },
]
